[package]
name = "chip8"
version = "0.1.0"
authors = ["stegmanh <stegman.holden@gmail.com>"]

[dependencies]
rand = "0.5"
minifb = { git = "https://github.com/stegmanh/rust_minifb.git" } 
rodio = "0.8"